language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
  - 5
sudo: false
before_install: npm install -g grunt-cli
before_script:
  - npm i -g bower
  - bower install
  - grunt
after_script:
  - npm run codecov
  - npm run coveralls
